-- TriCoach initial schema (SQLite).
-- UUID primary keys are stored as 16-byte BLOBs and generated by the app.
-- Dates are 'YYYY-MM-DD' TEXT; timestamps are RFC3339 TEXT. Enum-like columns
-- are TEXT and validated in the Rust domain layer.

CREATE TABLE users (
    id            BLOB PRIMARY KEY NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE athlete_profiles (
    user_id                 BLOB PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    display_name            TEXT NOT NULL,
    age                     INTEGER NOT NULL,
    weight_kg               REAL NOT NULL,
    experience_level        TEXT NOT NULL,   -- beginner | intermediate | advanced
    weekly_hours_available  REAL NOT NULL,
    resting_hr              INTEGER,
    max_hr                  INTEGER,
    updated_at              TEXT NOT NULL
);

CREATE TABLE training_plans (
    id             BLOB PRIMARY KEY NOT NULL,
    user_id        BLOB NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    race_distance  TEXT NOT NULL,            -- sprint | olympic | half_ironman | ironman
    race_date      TEXT NOT NULL,
    start_date     TEXT NOT NULL,
    total_weeks    INTEGER NOT NULL,
    status         TEXT NOT NULL DEFAULT 'active',  -- active | archived
    generated_by   TEXT NOT NULL,            -- gemini | rule_based
    summary        TEXT NOT NULL DEFAULT '',
    created_at     TEXT NOT NULL
);

CREATE INDEX idx_training_plans_user ON training_plans(user_id);

CREATE TABLE workouts (
    id                   BLOB PRIMARY KEY NOT NULL,
    plan_id              BLOB NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
    week_number          INTEGER NOT NULL,
    scheduled_date       TEXT NOT NULL,
    discipline           TEXT NOT NULL,      -- swim | bike | run | brick | strength | rest
    title                TEXT NOT NULL,
    description          TEXT NOT NULL,
    planned_duration_min INTEGER NOT NULL,
    planned_distance_km  REAL,
    intensity            TEXT NOT NULL,      -- recovery | endurance | tempo | threshold | vo2max
    status               TEXT NOT NULL DEFAULT 'scheduled', -- scheduled | completed | skipped
    created_at           TEXT NOT NULL
);

CREATE INDEX idx_workouts_plan ON workouts(plan_id);
CREATE INDEX idx_workouts_date ON workouts(scheduled_date);

CREATE TABLE workout_feedback (
    id                  BLOB PRIMARY KEY NOT NULL,
    workout_id          BLOB NOT NULL UNIQUE REFERENCES workouts(id) ON DELETE CASCADE,
    actual_duration_min INTEGER,
    actual_distance_km  REAL,
    avg_hr              INTEGER,
    max_hr              INTEGER,
    perceived_effort    INTEGER,             -- RPE 1-10
    notes               TEXT NOT NULL DEFAULT '',
    ai_feedback         TEXT NOT NULL DEFAULT '',
    created_at          TEXT NOT NULL
);

CREATE TABLE device_tokens (
    id          BLOB PRIMARY KEY NOT NULL,
    user_id     BLOB NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       TEXT NOT NULL,
    platform    TEXT NOT NULL,               -- ios | android
    created_at  TEXT NOT NULL,
    UNIQUE (user_id, token)
);

-- Busy calendar blocks used to schedule workouts around work/personal commitments.
CREATE TABLE schedule_blocks (
    id          BLOB PRIMARY KEY NOT NULL,
    user_id     BLOB NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    starts_at   TEXT NOT NULL,
    ends_at     TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE INDEX idx_schedule_blocks_user ON schedule_blocks(user_id);
